version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
        environment:
          JAVA_OPTS: -Xmx1536m
          GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
          paths:
            - ~/.gradle
      - run:
          name: decrypt keystore
          command: |
              if [ $CIRCLE_BRANCH = 'master' -o $CIRCLE_BRANCH = 'release' ]; then
                  openssl aes-256-cbc -k $KEYSTORE_DECRYPT_PASSWORD -d -in encrypted-droidkaigi-key -out release.keystore
              fi
      - run:
          name: decrypt json
          command: |
              if [ $CIRCLE_BRANCH = 'master' -o $CIRCLE_BRANCH = 'release' ]; then
                  openssl aes-256-cbc -k $JSON_DECRYPT_PASSWORD -d -in encrypted-google-services.json -out app/google-services.json
              fi
      - run:
          name: Test
          command: |
              if [ $CIRCLE_BRANCH = 'master' -o $CIRCLE_BRANCH = 'release' ]; then
                  ./gradlew --stacktrace testRelease
              else
                  ./gradlew --stacktrace test${APP_BUILD_TYPE^}
              fi
      - run:
          name: Build
          command: |
              if [ $CIRCLE_BRANCH = 'master' -o $CIRCLE_BRANCH = 'release' ]; then
                  ./gradlew --offline --stacktrace assembleRelease
              else
                  ./gradlew --offline --stacktrace assemble${APP_BUILD_TYPE^}
              fi
      - run:
          name: Check
          command: |
              if [ ! $CIRCLE_BRANCH = 'master' -a ! $CIRCLE_BRANCH = 'release' ]; then
                  ./gradlew --stacktrace lint${APP_BUILD_TYPE^}
                  ./gradlew --stacktrace ktlint${APP_BUILD_TYPE^}Check
                  bundle exec danger
              fi
      - run:
          name: Deploy
          command: |
              if [ $CIRCLE_BRANCH = 'master' ]; then
                  ./gradlew :app:uploadDeployGateRelease
              elif [[ "${CIRCLE_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                  echo "Deploy to Google Play"
                  openssl aes-256-cbc -k $PUBLISHER_KEYS_JSON_DECRYPT_PASSWORD -d -in encrypted-publisher-keys.json -out app/publisher-keys.json
                  ./gradlew publishApkRelease
              fi
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

# workaround for tag trigger
# because workflow git tag trigger does not work well
deployment:
  fake_for_deploy:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
