version: 2

jobs:
  build:
    docker:
      - image: punchdrunker/android-27-ruby
        environment:
          JAVA_OPTS: -Xmx1536m
          GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError"'
    steps:
      - checkout
      - restore_cache:
          key: sdks-licenses-build-tools-extras-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Bundle install
          command: bundle instal
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: sdks-licenses-build-tools-extras-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - /opt/android/sdk/licenses
            - /opt/android/sdk/build-tools
            - /opt/android/sdk/extras
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: decrypt keystore
          command: |
              if [ $CIRCLE_BRANCH = 'master' ]; then
                  openssl aes-256-cbc -k $KEYSTORE_DECRYPT_PASSWORD -d -in encrypted-droidkaigi-key -out release.keystore
              fi
      - run:
          name: decrypt json
          command: |
              if [ $CIRCLE_BRANCH = 'master' ]; then
                  openssl aes-256-cbc -k $JSON_DECRYPT_PASSWORD -d -in encrypted-google-services.json -out app/google-services.json
              fi
      - run:
          name: Test
          command: |
              if [ $CIRCLE_BRANCH = 'master' ]; then
                  ./gradlew --stacktrace testRelease
              else
                  ./gradlew --stacktrace test${APP_BUILD_TYPE^}
              fi
      - run:
          name: Build
          command: |
              if [ $CIRCLE_BRANCH = 'master' ]; then
                  ./gradlew --offline --stacktrace assembleRelease
              else
                  ./gradlew --offline --stacktrace assemble${APP_BUILD_TYPE^}
              fi
      - run:
          name: Check
          command: |
              if [ ! $CIRCLE_BRANCH = 'master' ]; then
                  ./gradlew --stacktrace lint${APP_BUILD_TYPE^}
                  ./gradlew --stacktrace ktlint${APP_BUILD_TYPE^}Check
                  bundle exec danger
              fi
      - run:
          name: Deploy
          command: ./deploy.sh
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
